### ISSUE TITLE
Can I import the oxlintrc.json content directly?

### ISSUE THREAD

**Issue by TommcyOWO** [52-entertainment/vite-plugin-oxlint#1]
I have an oxlintrc.json file, can I import the content directly?
oxlintrc.json like this
```json
{
    "env": {
      "browser": true
    },
    "globals": {
      "foo": "readonly"
    },
    "settings": {},
    "rules": {
      "eqeqeq": "warn"
    }
}
```

**Comment by arnriu** [comment]
Not currently @TommcyOWO , but I will make an update soon to include oxlintrc files.

**Comment by arnriu** [comment]
Version [1.0.4](https://github.com/52-entertainment/vite-plugin-oxlint/releases/tag/1.0.4) added config files support.
