### ISSUE TITLE
请问这个问题如何解决？

### ISSUE THREAD

**Issue by wzs28150** [52-entertainment/vite-plugin-oxlint#3]
![image](https://github.com/user-attachments/assets/81c6552b-93ad-4a30-abbd-b8ade9560706)
我是管理员下执行得命令，感觉是child_process.exec得问题，我的node 版本v20.8.1，我正常执行npx oxlint是没问题的

**Comment by yujiayinshi** [comment]
+1，windows上同样遇到此问题，请问你是怎么解决的？
